//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadanie10202
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Zadanie10202Entities : DbContext
    {
        public Zadanie10202Entities()
            : base("name=Zadanie10202Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Данные_партнёров> Данные_партнёров { get; set; }
        public virtual DbSet<Количества_продукции> Количества_продукции { get; set; }
        public virtual DbSet<Материалы> Материалы { get; set; }
        public virtual DbSet<Материалы_продукции> Материалы_продукции { get; set; }
        public virtual DbSet<Продукции> Продукции { get; set; }
        public virtual DbSet<Типы_материалов> Типы_материалов { get; set; }
        public virtual DbSet<Типы_партнёров> Типы_партнёров { get; set; }
        public virtual DbSet<Типы_продукции> Типы_продукции { get; set; }
        public virtual DbSet<Юридические_адреса> Юридические_адреса { get; set; }
    }
}
