//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadanie10202
{
    using System;
    using System.Collections.Generic;
    
    public partial class Данные_партнёров
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Данные_партнёров()
        {
            this.Количества_продукции = new HashSet<Количества_продукции>();
        }
    
        public int Номер_партнера { get; set; }
        public Nullable<int> Тип_партнера { get; set; }
        public string Наименование_партнера { get; set; }
        public string Директор { get; set; }
        public string Электронная_почта_партнера { get; set; }
        public string Телефон_партнера { get; set; }
        public Nullable<int> Юридический_адрес_партнера { get; set; }
        public string ИНН { get; set; }
        public Nullable<int> Рейтинг { get; set; }
    
        public virtual Типы_партнёров Типы_партнёров { get; set; }
        public virtual Юридические_адреса Юридические_адреса { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Количества_продукции> Количества_продукции { get; set; }
    }
}
