//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadanie10202
{
    using System;
    using System.Collections.Generic;
    
    public partial class Продукции
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Продукции()
        {
            this.Количества_продукции = new HashSet<Количества_продукции>();
            this.Материалы_продукции = new HashSet<Материалы_продукции>();
        }
    
        public int Номер_продукции { get; set; }
        public Nullable<int> Тип_продукции { get; set; }
        public string Наименование_продукции { get; set; }
        public string Артикул { get; set; }
        public Nullable<decimal> Минимальная_стоимость_для_партнера { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Количества_продукции> Количества_продукции { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Материалы_продукции> Материалы_продукции { get; set; }
        public virtual Типы_продукции Типы_продукции { get; set; }
    }
}
