//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadanie10202
{
    using System;
    using System.Collections.Generic;
    
    public partial class Типы_партнёров
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Типы_партнёров()
        {
            this.Данные_партнёров = new HashSet<Данные_партнёров>();
        }
    
        public int Номер_типа_партнёров { get; set; }
        public string Тип_партнёров { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Данные_партнёров> Данные_партнёров { get; set; }
    }
}
