//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadanie10202
{
    using System;
    using System.Collections.Generic;
    
    public partial class Типы_материалов
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Типы_материалов()
        {
            this.Материалы = new HashSet<Материалы>();
        }
    
        public int Номер_типа_материала { get; set; }
        public string Тип_материала { get; set; }
        public Nullable<double> Процент_брака_материала { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Материалы> Материалы { get; set; }
    }
}
