//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadanie10202
{
    using System;
    using System.Collections.Generic;
    
    public partial class Юридические_адреса
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Юридические_адреса()
        {
            this.Данные_партнёров = new HashSet<Данные_партнёров>();
        }
    
        public int Номер_юридического_адреса { get; set; }
        public string Индекс { get; set; }
        public string Область { get; set; }
        public string Город { get; set; }
        public string Улица { get; set; }
        public Nullable<int> Дом { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Данные_партнёров> Данные_партнёров { get; set; }
    }
}
